[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = true

[dependencies]
format_no_std = "1.2.0"

[build-dependencies]
cc = "1.0"